Cleaning up bugs introduced by merge (and some other bugs). Specifically
> In file included from arch/arm/mach-stmp3xxx/stmp378x_devb.c:36:0:
> arch/arm/mach-stmp3xxx/include/mach/stmp3xxx.h:93:1: warning: function declaration isn't a prototype

FIXED by adding (void) in fn decl

> arch/arm/mach-stmp3xxx/stmp378x_devb.c: In function 'stmp378x_devb_init':
> arch/arm/mach-stmp3xxx/stmp378x_devb.c:349:10: error: 'stmp3xxx_udc' undeclared (first use in this function)
j
> arch/arm/mach-stmp3xxx/stmp378x_devb.c:349:10: note: each undeclared identifier is reported only once for each funct\
on it appears in
> arch/arm/mach-stmp3xxx/stmp378x_devb.c:350:25: error: 'usb_phy_enable' undeclared (first use in this function)
> arch/arm/mach-stmp3xxx/stmp378x_devb.c:351:10: error: 'stmp3xxx_ehci' undeclared (first use in this function)

fixed merge errors per
https://github.com/clearwater/chumby-linux/commit/60420e52d9ed3164ce85b2d237e28709c2de3510#diff-5

> arch/arm/mach-stmp3xxx/stmp378x_devb.c: In function 'chumbyrev_setup':
> arch/arm/mach-stmp3xxx/stmp378x_devb.c:375:1: warning: no return statement in function returning non-void

added return 0 to end of chumby-specific function